camera:
    fps: 60
    display: true
    width: 640
    height: 480
    urls:
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
    ids:
        - 'vid-walk-1'
        - 'vid-walk-2'
        - 'vid-walk-3'
        - 'vid-walk-4'
        - 'vid-walk-5'
        - 'vid-walk-6'
        - 'vid-walk-7'
        - 'vid-walk-8'

kafka:
  bootstrap.servers: "localhost:9092"
  topic: "video-stream-event"
  acks: "all"
  retries: 1
  batch.size: 20971520        # 20MB
  linger.ms: 5
  compression.type: "gzip"
  message.max.bytes: 20971520 # 20MB
