camera:
    fps: 60
    display: true
    width: 1024
    height: 576
    urls:
        - 'resources/car.mp4'
        - 'resources/walk.mp4'
    ids:
        - 'vid-car'
        - 'vid-walk'

kafka:
  bootstrap.servers: "kafka:9092"
  topic: "video-stream-event"
  acks: "all"
  retries: 1
  batch.size: 20971520
  linger.ms: 5
  compression.type: "gzip"
  max.request.size: 10485760 # 10 mb
