camera:
    fps: 60
    display: true
    width: 1024
    height: 576
    urls:
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 'resources/walk.mp4'
        - 0
        - 0
    ids:
        - 'vid-walk-1'
        - 'vid-walk-2'
        - 'vid-walk-3'
        - 'vid-walk-4'
        - 'cam-0-1'
        - 'cam-0-2'