services:
  minio:
    image: docker.io/bitnami/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: Minio12345* 
      # MINIO_DEFAULT_BUCKETS: test
    volumes:
      - ./minio_data:/data